title: Didulani Acharige
logo: /assets/img.jpg
description: I am a confident, innovative, flexible, fast-learning individual who graduated with my Ph.D. in the Department of Mechanical and Materials Engineering, Faculty of Engineering at Western University in October 2024. My thesis is to explore the utilization of machine learning and deep learning techniques for the inverse design of nanophotonics. 
#Site Author
author: 
    name: Didulani Acharige
    location: Ontario, Canada
    email: didulanidayarathna@gmail.com
    LinkedIN: "https://www.linkedin.com/in/didulani-acharige/"
    github: "https://github.com/DidulaniDayarathna"
show_downloads: False
theme: jekyll-theme-minimal
